### ISSUE TITLE
Blogs page containers commenting and creating get featured section and editing the containers

### ISSUE THREAD

**Issue by ghousetazeem** [LernTek/LernTek-Main#7]

**Comment by MohammedMaaz0213** [comment]
I want to work on this

**Comment by ghousetazeem** [comment]
Sure but I want the update till tomorrow evening 11PM

**Comment by MohammedMaaz0213** [comment]
![No-Memes-15](https://github.com/LernTek/LernTek-Main/assets/77317846/76ecf709-7102-46cc-a79c-47859d7c2580)

**Comment by MohammedMaaz0213** [comment]
Sure I will do it by tomorrow
